---
- name: Configure vmbr0 Bridge
  community.proxmox.proxmox_node_network:
    api_user: "{{ pve_api_user | default('root@pam') }}"
    api_token_id: "{{ pve_api_token_id }}"
    api_token_secret: "{{ pve_api_token_secret }}"
    api_host: "{{ pve_host | default(ansible_host) }}"
    api_port: "8006"
    validate_certs: false
    node: "{{ ansible_facts['hostname'] }}"
    iface: "{{ pve_bridge_name | default('vmbr0') }}"
    iface_type: bridge
    cidr: "{{ pve_bridge_cidr | default('192.168.1.100/24') }}"
    bridge_ports: "{{ pve_bridge_ports | default(ansible_facts['default_ipv4']['interface']) }}"
    autostart: true
    state: present

- name: Apply Network Configuration
  community.proxmox.proxmox_node_network:
    api_user: "{{ pve_api_user | default('root@pam') }}"
    api_token_id: "{{ pve_api_token_id }}"
    api_token_secret: "{{ pve_api_token_secret }}"
    api_host: "{{ ansible_host }}"
    validate_certs: false
    node: "{{ ansible_facts['hostname'] }}"
    state: apply

- name: Create SDN Simple Zone
  community.proxmox.proxmox_zone:
    api_user: "{{ pve_api_user | default('root@pam') }}"
    api_token_id: "{{ pve_api_token_id }}"
    api_token_secret: "{{ pve_api_token_secret }}"
    api_host: "{{ ansible_host }}"
    validate_certs: false
    zone: "{{ pve_sdn_zone_name | default('dmz') }}"
    type: simple
    state: present

- name: Create SDN DMZ Vnet
  community.proxmox.proxmox_vnet:
    api_user: "{{ pve_api_user | default('root@pam') }}"
    api_token_id: "{{ pve_api_token_id }}"
    api_token_secret: "{{ pve_api_token_secret }}"
    api_host: "{{ ansible_host }}"
    validate_certs: false
    vnet: "{{ pve_sdn_vnet_name | default('vnet-dmz') }}"
    zone: "{{ pve_sdn_zone_name | default('dmz') }}"
    tag: "{{ pve_sdn_tag | default(omit) }}"
    state: present
