---
- name: Ensure Docker network for Traefik exists
  community.docker.docker_network:
    name: traefik-public
    state: present

- name: Deploy Traefik Docker Container
  community.docker.docker_container:
    name: traefik
    image: "traefik:v3.0"
    state: started
    restart_policy: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - name: traefik-public
