---
- name: Restart PVEproxy
  ansible.builtin.service:
    name: pveproxy
    state: restarted

- name: Restart SSHD
  ansible.builtin.service:
    name: ssh
    state: restarted

- name: Restart Fail2Ban
  ansible.builtin.service:
    name: fail2ban
    state: restarted

- name: Update Initramfs
  ansible.builtin.command: "update-initramfs -u"
  changed_when: true

- name: Restart Prometheus
  ansible.builtin.service:
    name: prometheus
    state: restarted

- name: Restart Telegraf
  ansible.builtin.service:
    name: telegraf
    state: restarted

- name: Restart Loki
  ansible.builtin.service:
    name: loki
    state: restarted

- name: Restart Promtail
  ansible.builtin.service:
    name: promtail
    state: restarted

- name: Restart Grafana
  ansible.builtin.service:
    name: grafana-server
    state: restarted
