#!/usr/bin/env python3
"""Render ansible/inventory/hosts.yml from `tofu output -json`.

Consumes the lxc_service facts surfaced in tofu/outputs.tf
(docker_host_name / docker_host_ipv4 and plex_name / plex_ipv4) so the
Ansible config layer derives host facts from the IaC layer instead of
hard-coding them (design §Data Models). The `*_ipv4` outputs are best-effort
and may be null until the CT network is up; in that case we fall back to the
static design address (docker_host .111, plex .110) and annotate the host so
the file is always valid. Stdlib only.

Run via `mise run gen-inventory`.
"""

import json
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
TOFU_DIR = REPO_ROOT / "tofu"
INVENTORY = REPO_ROOT / "ansible" / "inventory" / "hosts.yml"

# Static fallbacks from the design (tofu/locals.tf net .111/.110 /24) used when
# the Tofu state has no live IP yet (e.g. before `tofu apply`).
FALLBACK_IP = "192.168.1.111"
PLEX_FALLBACK_IP = "192.168.1.110"
ANSIBLE_USER = "root"


def tofu_outputs() -> dict:
    """Return the parsed `tofu output -json` map (empty if no state yet)."""
    result = subprocess.run(
        ["tofu", "output", "-json"],
        cwd=TOFU_DIR,
        capture_output=True,
        text=True,
    )
    if result.returncode != 0:
        sys.stderr.write(result.stderr)
        raise SystemExit(f"tofu output failed (exit {result.returncode})")
    return json.loads(result.stdout or "{}")


def render(outputs: dict) -> str:
    def value(key, default=None):
        return (outputs.get(key) or {}).get("value", default)

    name = value("docker_host_name") or "docker-host"
    ipv4 = value("docker_host_ipv4")
    host_comment = ""
    if not ipv4:
        ipv4 = FALLBACK_IP
        host_comment = "  # tofu output had no live IP yet; static design fallback"

    plex_name = value("plex_name") or "plex"
    plex_ipv4 = value("plex_ipv4")
    plex_comment = ""
    if not plex_ipv4:
        plex_ipv4 = PLEX_FALLBACK_IP
        plex_comment = "  # tofu output had no live IP yet; static design fallback"

    return (
        "---\n"
        "# GENERATED by scripts/gen_inventory.py (`mise run gen-inventory`) from\n"
        "# `tofu output -json`. Edit the Tofu config/outputs, not this file.\n"
        "all:\n"
        "  children:\n"
        "    docker_host:\n"
        "      hosts:\n"
        f"        {name}:\n"
        f"          ansible_host: {ipv4}{host_comment}\n"
        f"          ansible_user: {ANSIBLE_USER}\n"
        "    plex:\n"
        "      hosts:\n"
        f"        {plex_name}:\n"
        f"          ansible_host: {plex_ipv4}{plex_comment}\n"
        f"          ansible_user: {ANSIBLE_USER}\n"
    )


def main() -> int:
    outputs = tofu_outputs()
    INVENTORY.parent.mkdir(parents=True, exist_ok=True)
    INVENTORY.write_text(render(outputs))
    print(f"wrote {INVENTORY}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
