---
- name: Bootstrap Ansible Python Environment
  ansible.builtin.import_playbook: bootstrap-ansible.yml

- name: Bootstrap Proxmox Core Services
  hosts: proxmox_hosts
  roles:
    - pve_base
    - plex
    - pihole
    - traefik
    - bitwarden
    - uptimekuma
